### ISSUE TITLE
Handle is always null.

### ISSUE THREAD

**Issue by greg-lancet** [TechnikEmpire/WinDivertSharp#11]
When opening a WinDivert handle it is always null, code used is :
` var WinDivertHandle = WinDivert.WinDivertOpen("tcp", WinDivertLayer.Network, 0, WinDivertOpenFlags.None);`
I check if it is an IntPtr equal to 0 and it is, as well as when I run it it returns an error which is 6 (handle is invalid). I'm wondering if it comes from the library or me misusing it.

**Comment by TechnikEmpire** [comment]
Has to be run as administrator. 

I saw a bug thread on windivert that Microsoft had flagged the driver as a virus. It could be that the windows driver subsystems is refusing to load it.

Call marshal.getlasterror or whatever the function is.

**Comment by TechnikEmpire** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getlastwin32error?view=netcore-3.1

**Comment by TechnikEmpire** [comment]
@Swourire let me know when you run as admin and get the win32 error code.

**Comment by greg-lancet** [comment]
Yeah I did get marshall get lasterror, didn't try run as admin but the error code was 6.

**Comment by TechnikEmpire** [comment]
You have to run as admin. It's a kernel driver.
