### ISSUE TITLE
WinDivertRecv read length incorrect in windivert 2.2.2

### ISSUE THREAD

**Issue by tomlevels** [TechnikEmpire/WinDivertSharp#18]
When updating Windivert from 1.4 to 2.2.2, I noticed the read length of WinDivertRecv is not correct. I looked a bit and found out that the read length can be retrieved by getting the timestamp field of the address. Can this mapping be fixed (if you are still active in this repository)?

**Comment by TechnikEmpire** [comment]
WinDivert uses semver. 1.4 -> 2.* means a breaking API change. It's been 5 years since I've looked at this repository but I can pretty safely guess that it's not compatible.
