### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by joveice** [TechnikEmpire/WinDivertSharp#5]
I'm trying to understand how I can set this up but I have no clue, I have tried to open it in the Rider and VS, and it just flashes with red errors everywhere.
I have looked on all of these:
https://github.com/TechnikEmpire/WinDivertSharp
https://github.com/TechnikEmpire/DivertPInvoke
https://github.com/TechnikEmpire/Divert.Net

What do I need to set this up and get it running?
I'm currently using this in a python project https://github.com/ffalcinelli/pydivert which was no problem to setup.

**Comment by TechnikEmpire** [comment]
Well I was happy to help until I hit the end of your bug ticket, where you seem to imply there's something fundamentally wrong my library because you're frustrated and don't understand what the unsafe switch is.

If you'd like to try again, feel free to leave a comment about how you're encountering an error that you don't understand, provide a stack trace and or ide error output, followed by a polite request for my free professional help that you're not entitled to.

**Comment by TechnikEmpire** [comment]
This is why we shouldn't make things up, like "so and sos library works amazing unlike yours"

https://github.com/ffalcinelli/pydivert/issues/38

**Comment by joveice** [comment]
What? I'm not saying there is anything wrong with your lib anywhere, where do you get that from??

I'm asking for _*help*_ as I have not used your lib before and I could not get it to work and found no setup / requirements for it.

The pydivert thing is just how the lib is created, you can go around it by putting it in a thread.

**Comment by TechnikEmpire** [comment]
Well, generally when you start of with "there's just red lines everywhere" and then follow it by "this other library that does the same thing works fine", that's not really looking for help.

Tell me what errors you're actually getting. The red squiggly lines will correspond to an error in the `Errors` window. Almost surely you simply need to right click on your project, and enable unsafe code in the compilation section.

This project uses WinDivertSharp.

https://github.com/TechnikEmpire/CitadelCore.Windows

Specifically:

https://github.com/TechnikEmpire/CitadelCore.Windows/blob/master/CitadelCore.Windows/Diversion/WindowsDiverter.cs

**Comment by TechnikEmpire** [comment]
Btw, to answer your bug ticket about PyDivert, almost certainly they or you were not using the `RecvEx` function variant in WinDivert, which means it's an infinitely blocking call until the driver returns something. Don't use `Recv`, use `RecvEx` exactly as I'm using it in CitadelCore.Windows.

**Comment by joveice** [comment]
Now you have been double helpful, thank you.

One of the issues was that I did not have System.Memory which was sorted by getting that.

I don't have the PC in front of me right now so I will come back with a stack trace and exact errors.
Again, thanks.

**Comment by TechnikEmpire** [comment]
@joveice If you install this library from Nuget, it should pull down System.Memory for you automatically.

All the best with your project.

**Comment by joveice** [comment]
@TechnikEmpire I will try that out.

Thank you.

**Comment by joveice** [comment]
Okey, I started a fresh project and included this thru nuget, I'm trying to use the sandbox part here, but I'm gonna guess it's for an older version or I'm still missing something.

These are the errors
```
  Program.cs(104, 13): [CS0246] The type or namespace name 'Span<>' could not be found (are you missing a using directive or an assembly reference?)
  Program.cs(181, 133): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
  Program.cs(181, 205): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
  Program.cs(185, 133): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
  Program.cs(185, 205): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
```
So looks like System.Memory does not get included with it, I added this and now I'm left with this
```
  Program.cs(172, 31): [CS1501] No overload for method 'WinDivertHelperParsePacket' takes 9 arguments
  Program.cs(181, 133): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
  Program.cs(181, 205): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
  Program.cs(185, 133): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
  Program.cs(185, 205): [CS1061] 'ushort' does not contain a definition for 'SwapByteOrder' and no accessible extension method 'SwapByteOrder' accepting a first argument of type 'ushort' could be found (are you missing a using directive or an assembly reference?)
```

So is that code obsolete or am I missing something more?

**Comment by joveice** [comment]
Not sure if whats easier, to get ^ to work or explain to me how I can do what I had plans to do:
A loop that reads with a filter like the sandbox code seems to do, then read the IP's and send / drop packets

**Comment by TechnikEmpire** [comment]
@joveice ah, yep that code is out of date. I'll open a ticket for it.

The CitadelCore.Windows code will be up to date. I don't have the time to do it right now, but I'll open a ticket on here to sync the example code. Thanks for reporting.

**Comment by joveice** [comment]
Okey, that was a bit too much C# for me to understand as of now. I'll just wait for whenever your example is done.

This library does look really good tho!
