### ISSUE TITLE
Issue while sending my own packet

### ISSUE THREAD

**Issue by xzVice** [TechnikEmpire/WinDivertSharp#7]
Hi,
I'm trying to send my own packet via udp but when sending it I get error code 87. It should be bad parameter err. but I'm providing the correct params...

Here's the code

`
var buffer1 = StringToByteArray("HEX STUFF");
WinDivertBuffer buff1 = new WinDivertBuffer(buffer1);

var checksum = WinDivert.WinDivertHelperCalcChecksums(packet, (uint)packet.Length, ref addr, WinDivertChecksumHelperParam.All);
                            

uint length = (uint) i;
                            
if (!WinDivert.WinDivertSend(handle, buff1, (uint)packet.Length,  ref addr, ref length))
{
                                Console.WriteLine("Write Err: {0}", Marshal.GetLastWin32Error());
}
`

**Comment by TechnikEmpire** [comment]
What basil said in his repo. Check that your packet is even valid in the first place. Use the helper function parse packet or manually check your work. Make sure length is correct and headers are correct.

**Comment by xzVice** [comment]
Mmmh, will packet parser correct the headers and how can I check if the lenght is correct, I mean is the length only the payload’s length or do i have to add every other header length to it?

**Comment by xzVice** [comment]
I've tried using packet parser but that didn't work... I've also tried to bruteforce the length to check which one would work but none worked...
Here's the updated code:

```
if (SendSpecial)
{
    SendSpecial = false;
    
    Console.WriteLine("Building the special packet...");

    var buffer = StringToByteArray("HEX STUFF");
    WinDivertBuffer buff = new WinDivertBuffer(buffer);
    
    var checksum = WinDivert.WinDivertHelperCalcChecksums(buff, (uint) buff.Length, ref addr, WinDivertChecksumHelperParam.All);

    var payload = new Span<byte>();

    WinDivert.WinDivertHelperParsePacket(buff, (uint) buffer.Length, ref ipv4Header, ref ipv6Header,
        ref icmpV4Header, ref icmpV6Header, ref tcpHeader, ref udpHeader, ref payload);

    Console.WriteLine("Payload len:" + payload.ToArray().Length);
    
    if (!WinDivert.WinDivertSend(handle, buff, (uint)payload.Length, ref addr))
    {
        Console.WriteLine("Write Special Packet Err: {0}", Marshal.GetLastWin32Error());
    }
    else
    {
        Console.WriteLine("Special Packet doneeeee");
    }
}
```

**Comment by TechnikEmpire** [comment]
Closing as this is a non-issue.
