### ISSUE TITLE
Port/SeqNum have bytes reversed

### ISSUE THREAD

**Issue by kOchirasu** [TechnikEmpire/WinDivertSharp#9]
I have to reverse the byes in these values in order to use them properly. I feel like the library should be the one handling this.

**Comment by TechnikEmpire** [comment]
Its a simple call to IPAddress.NetworkToHostOrder and you should only be calling it once per condition for the lifetime of your application.

It makes little to no sense to force function calls every single time to covert naturally big endian values to little endian and incur performance penalties when a correctly engineered application doesn't need to do this.

Suggest you reengineer your app.

**Comment by kOchirasu** [comment]
If you do the conversion on value retrieval, there is no performance penalty unless the value is retrieved. Stuff like sequence number is different on every packet, are you telling me to manually increment a sequence number counter? Seems like unnecessary complexity to me.

**Comment by TechnikEmpire** [comment]
Alright granted but this is a wrapper around windivert and it doesn't auto convert. Idea was to stay close to the original design.

I'm writing my own kernel driver so I'm not investing anymore work into windivert.
